language: ruby
rvm:
  - 2.1.0
install: 
  - bundle install
cache: bundler
before_script: 
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.6.1 bash
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=chromium-browser  
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: rake travis:travis