#!/bin/bash

# This script should be placed in /etc/cron.daily to check the cards status
# every day and send an email to the card's owner accordingly.

set -e

cd /home/app/resj
setuser app bundle exec rake cards_update:check

# logs a message with the standard logger utility
logger cards-check script executed