name: cucumber

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  cucumber:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker compose
        run: docker-compose -f docker-compose-cucumber.yml up --abort-on-container-exit --exit-code-from test-cucumber
  
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    container: ruby:2.6.3-alpine
    env:
      RAILS_ENV: test
      POSTGRES_HOST: pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

    services:
      pg:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      selenium:
        image: selenium/standalone-chrome:94.0.4606.61
      
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          apk add --update --no-cache bash build-base nodejs sqlite-dev tzdata postgresql-dev yarn
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install
      - name: Create database
        run: |
          bundle exec rake db:setup
          bundle exec rake db:test:prepare
      - name: Run tests
        run: bundle exec rake spec